veri<-read.csv("heart.csv", header=TRUE, sep=",")
summary(veri)
library(readxl)
veri1 <- read_excel("C:/Users/yaprak/Downloads/Raisin_Dataset/Raisin_Dataset/Raisin_Dataset.xlsx")
View(Raisin_Dataset)
install.packages("tidyverse")
library(tidyverse)
attach(Raisin_Dataset)
summary(Raisin_Dataset)

tablex<-table(Class)
hist(Area)
shapiro.test(Area)

set.seed(1)
summary(sample(Raisin_Dataset$Area, size=50))
set.seed(2)
summary(sample(Raisin_Dataset$MajorAxisLength, size=50))
set.seed(3)
summary(sample(Raisin_Dataset$MinorAxisLength, size=50))
set.seed(4)
summary(sample(Raisin_Dataset$Eccentricity, size=50))
set.seed(5)
summary(sample(Raisin_Dataset$ConvexArea, size=50))
set.seed(6)
summary(sample(Raisin_Dataset$Extent, size=50))
set.seed(7)
summary(sample(Raisin_Dataset$Perimeter, size=50))
set.seed(8)
table(sample(Raisin_Dataset$Class, size=50))

set.seed(1)
hist(sample(Raisin_Dataset$Area, size=50))
set.seed(2)
hist(sample(Raisin_Dataset$MajorAxisLength, size=50))
set.seed(3)
hist(sample(Raisin_Dataset$MinorAxisLength, size=50))
set.seed(4)
hist(sample(Raisin_Dataset$Eccentricity, size=50))
set.seed(5)
hist(sample(Raisin_Dataset$ConvexArea, size=50))
set.seed(6)
hist(sample(Raisin_Dataset$Extent, size=50))
set.seed(7)
hist(sample(Raisin_Dataset$Perimeter, size=50))
set.seed(8)
hist(table(sample(Raisin_Dataset$Class, size=50)))

set.seed(1)
shapiro.test(sample(Raisin_Dataset$Area, size=50))
set.seed(2)
shapiro.test(sample(Raisin_Dataset$MajorAxisLength, size=50))
set.seed(3)
shapiro.test(sample(Raisin_Dataset$MinorAxisLength, size=50))
set.seed(4)
shapiro.test(sample(Raisin_Dataset$Eccentricity, size=50))
set.seed(5)
shapiro.test(sample(Raisin_Dataset$ConvexArea, size=50))
set.seed(6)
shapiro.test(sample(Raisin_Dataset$Extent, size=50))
set.seed(7)
shapiro.test(sample(Raisin_Dataset$Perimeter, size=50))

dataset1<-data.matrix(Raisin_Dataset)
dataset1<-as.data.frame(dataset1)
table(dataset1$Class)
set.seed(9)
shapiro.test(sample(dataset1$Class, size=50))
set.seed(9)
hist(table(sample(dataset1$Class, size=50)))

set.seed(3)
t.test(sample(Raisin_Dataset$MinorAxisLength, size=50), mu=254.5, alternative="two.sided", conf.level = 0.95)

set.seed(3)
t.test(sample(Raisin_Dataset$MinorAxisLength, size=50), mu=254.5, alternative="less", conf.level = 0.95)
 
Kecimen<-c(Raisin_Dataset$MajorAxisLength[1:450])
Besni<-c(Raisin_Dataset$MajorAxisLength[451:900])

wilcox.test(Kecimen,Besni)

#Kecimen<-c(Raisin_Dataset$Area[1:450])
#Besni<-c(Raisin_Dataset$Area[451:900])

install.packages('corrplot')
library(corrplot)
korelasyon<-cor(dataset1)
corrplot(korelasyon, method="circle")

plot(Raisin_Dataset$Area,Raisin_Dataset$MajorAxisLength)
install.packages("MASS")
library(MASS)
regresyon<-lm(Raisin_Dataset$Area~Raisin_Dataset$MajorAxisLength, data=Raisin_Dataset)
summary(regresyon)
shapiro.test(hata)

predict(regresyon,newdata=data.frame(X=(c(100,200))))
